Minors
AS-kilta/ASweb pull request #162
Opened 2024-09-01 11:03 UTC by ileskanRepot

Make page for minors

2024-09-01 14:22 UTC, ileskanRepot commented
When `/studies` path is merged `minors` need to be moved from `/guild/minors` to `/studies/minors`

2024-09-04 00:17 UTC, jyrge commented on src/components/minors/Minors.tsx
> +        {minorData.whatMasters.info[lang] != '' && minorData.whatMasters.info[lang]}
Oliko tässä ajatuksena ensin kokeilla, onko tuo minorData.whatMasters.info[lang] truthy vai kokeilla, ettei se ole täsmälleen tyhjä string? Ensimmäisessä tapauksessa Boolean(minorData.whatMasters.info[lang]) olisi se, mitä haetaan minorData.whatMasters.info[lang] != '' sijaan. Ja tässä tilanteessa ehkä joka tapauksessa oikea vaihtoehto, koska tuo voisi mahdollisesti olla myös undefined.

Kannattaa olla yleensä ottaen varovainen JS:ssä != operaattorin kanssa, se yrittää suorittaa tyyppimuunnoksen vertailussa. !== vertailee myös tyyppiä.

2024-09-04 00:20 UTC, jyrge commented on src/components/minors/Minors.tsx
> +        {minorData.whatCourses.info[lang] != '' && minorData.whatCourses.info[lang]}
Tässä sama

2024-09-04 00:35 UTC, jyrge commented on src/components/minors/Minors.tsx
> +  // console.log('WEE');
veks

2024-09-04 00:38 UTC, jyrge commented on src/components/minors/Minors.tsx
> +              <Minor minorData={entry} lang={lang}></Minor>
Tästä self-closing tagi, kun tuo komponentti ei ota childreneitä.

2024-09-04 01:04 UTC, jyrge requested changes
Yleensä ottaen näyttää ihan hyvältä. CSS:n kannalta noille boksien teksteille voisi olla vähän enemmän riviväliä, parantaa luettavuutta. Koodin kannalta muuttujien ym. nimeämisiä voisi vähän parannella. Katso kommentit.

2024-09-04 01:04 UTC, jyrge commented on src/components/minors/Minors.tsx
> +    fi: 'Linkku sivuaineen sivuille',
Linkki

2024-09-04 10:01 UTC, ileskanRepot commented on src/components/minors/Minors.tsx
> +        {minorData.whatMasters.info[lang] != '' && minorData.whatMasters.info[lang]}
Tarkoitus oli tarkistaa onko kyseinen muuttuja tyhjä. Kyseinen muuttuja on aina olemassa (mikäli tyyppiskriptiin on luottaminen), sillä se ei ole optional arvo. Mutta näköjään Reacti ignoraa "kentän" jos kyseinen kenttä on tyhjä.

2024-09-04 10:04 UTC, ileskanRepot commented
> Yleensä ottaen näyttää ihan hyvältä. CSS:n kannalta noille boksien teksteille voisi olla vähän enemmän riviväliä, parantaa luettavuutta. Koodin kannalta muuttujien ym. nimeämisiä voisi vähän parannella. Katso kommentit.
> 
> Sisältö varmaan katsotaan tarkemmin kuntoon?

Onko jotain specifiä rivinväliä mikä halutaan. Laitoin nyt rivinväliksi 140%. Ja sisällöstä en tiedä. Sain Mikhailta PDF:n, jossa oli noi tiedot. Saattaa tulla enemmän, mutta en usko

2024-09-04 15:57 UTC, jyrge commented on src/components/minors/Minors.tsx
> +        {minorData.whatMasters.info[lang] != '' && minorData.whatMasters.info[lang]}
Jos noista YAMLeista jostain puuttuu kyseinen kenttä, se arvo on null. TypeScriptin tyypitys ei ota kantaa siihen, mitä Gatsby parsii buildatessaan omiin tietomalleihinsa, vaan enemmänkin siihen, että devaaja pysyy tyypityksen rajoissa. Niitä varten voi toki pakottaa halutessaan oman GraphQL-schemensä, jota voi muokata gatsby-node.js:ssä. Tällöin pystyy tarkemmin pakottamaan YAMLeissa pysymään oikeassa formaatissa. Joissain tapauksissa niin on tehty, mutta en tiedä onko tässä välttämättä tarpeellista.

Nykyään Gatsby muuten osaa generoida automaattisesti tyypit nimetyille GraphQL-kyselyille, mutta ei olla tässä käytetty sitä ([linkki](https://www.gatsbyjs.com/blog/gatsby-5-typescript-and-generated-graphql-types-a-walkthrough/)). Mutta tuo tosiaan liittyy TypeScript-tyyppeihin, GraphQL API:n kautta voi edelleen tulla ihan mitä vaan.

Tässä kohtaa taisit joka tapauksessa vaihtaa oikeastaan yksinkertaisimpaan toimivaan ratkaisuun eli siltä osin homma ok.

2024-09-04 16:12 UTC, jyrge commented
> > Yleensä ottaen näyttää ihan hyvältä. CSS:n kannalta noille boksien teksteille voisi olla vähän enemmän riviväliä, parantaa luettavuutta. Koodin kannalta muuttujien ym. nimeämisiä voisi vähän parannella. Katso kommentit.
> > Sisältö varmaan katsotaan tarkemmin kuntoon?
> 
> Onko jotain specifiä rivinväliä mikä halutaan. Laitoin nyt rivinväliksi 140%. Ja sisällöstä en tiedä. Sain Mikhailta PDF:n, jossa oli noi tiedot. Saattaa tulla enemmän, mutta en usko

main.scss:ssä on laitettu 1.6, mutta lähtökohtaisesti katsoisin, mikä näyttää hyvältä.

> > Yleensä ottaen näyttää ihan hyvältä. CSS:n kannalta noille boksien teksteille voisi olla vähän enemmän riviväliä, parantaa luettavuutta. Koodin kannalta muuttujien ym. nimeämisiä voisi vähän parannella. Katso kommentit.
> > Sisältö varmaan katsotaan tarkemmin kuntoon?
> 
> Onko jotain specifiä rivinväliä mikä halutaan. Laitoin nyt rivinväliksi 140%. Ja sisällöstä en tiedä. Sain Mikhailta PDF:n, jossa oli noi tiedot. Saattaa tulla enemmän, mutta en usko

Muualla on taidettu käyttää yleisesti tekstille 1.6.

2024-11-02 19:07 UTC, merged